In [2]:
from pycaret.regression import *
import pandas as pd

In [3]:
df = pd.read_csv("C:/Users/82108/OneDrive/바탕 화면/git/han_river_water_level/datafile.csv", index_col = 0)
pdf = pd.read_csv("C:/Users/82108/OneDrive/바탕 화면/git/han_river_water_level/awsfile.csv",index_col = 0)

In [4]:
df1 = df.drop(columns = ["wl_1018680","wl_1018683","wl_1019630"])
df2 = df.drop(columns = ["wl_1018662","wl_1018683","wl_1019630"])
df3 = df.drop(columns = ["wl_1018680","wl_1018662","wl_1019630"])
df4 = df.drop(columns = ["wl_1018680","wl_1018683","wl_1018662"])
pdf1 = pdf.drop(columns = ["wl_1018680","wl_1018683","wl_1019630"])
pdf2 = pdf.drop(columns = ["wl_1018662","wl_1018683","wl_1019630"])
pdf3 = pdf.drop(columns = ["wl_1018680","wl_1018662","wl_1019630"])
pdf4 = pdf.drop(columns = ["wl_1018680","wl_1018683","wl_1018662"])

In [5]:
reg_test_1 = setup(data= df1, target="wl_1018662", train_size=0.7, fold=5, session_id = 152, imputation_type='iterative', iterative_imputation_iters=10, categorical_iterative_imputer='lightgbm',silent = True)

In [6]:
best1 = compare_models(sort='RMSE', n_select=4)

In [7]:
blender1 = blend_models(estimator_list=best1)

In [8]:
finalm1 = finalize_model(blender1)
pred1 = predict_model(finalm1, data = pdf1)

In [9]:
reg_test_2 = setup(data= df2, target="wl_1018680", train_size=0.7, fold=5, session_id = 152, imputation_type='iterative', iterative_imputation_iters=10, categorical_iterative_imputer='lightgbm',silent = True)

In [10]:
best2 = compare_models(sort='RMSE', n_select=4)

In [11]:
blender2 = blend_models(estimator_list=best2)

IntProgress(value=0, description='Processing: ', max=6)

Initiated  . . . . . . . . . . . . . . . . . .          00:49:59
Status     . . . . . . . . . . . . . . . . . .   Fitting 5 Folds
Estimator  . . . . . . . . . . . . . . . . . .  Voting Regressor

Empty DataFrame
Columns: [Fold, MAE, MSE, RMSE, R2, RMSLE, MAPE]
Index: []

In [ ]:
finalm2 = finalize_model(blender2)
pred2 = predict_model(finalm2, data = pdf2)

In [12]:
reg_test_3 = setup(data= df3, target="wl_1018683", train_size=0.7, fold=5, session_id = 152, imputation_type='iterative', iterative_imputation_iters=10, categorical_iterative_imputer='lightgbm',silent = True)

In [13]:
best3 = compare_models(sort='RMSE', n_select=4)

In [14]:
blender3 = blend_models(estimator_list=best3)

In [15]:
finalm3 = finalize_model(blender3)
pred3 = predict_model(finalm3, data = pdf3)

In [16]:
reg_test_4 = setup(data= df4, target="wl_1019630", train_size=0.7, fold=5, session_id = 152, imputation_type='iterative', iterative_imputation_iters=10, categorical_iterative_imputer='lightgbm',silent = True)

In [17]:
best4 = compare_models(sort='RMSE', n_select=4)

In [18]:
blender4 = blend_models(estimator_list=best4)

In [19]:
finalm4 = finalize_model(blender4)
pred4 = predict_model(finalm4, data = pdf4)

In [31]:
pred1 = pred1["Label"].reset_index(drop=True)
pred2 = pred2["Label"].reset_index(drop=True)
pred3 = pred3["Label"].reset_index(drop=True)
pred4 = pred4["Label"].reset_index(drop=True)

In [32]:
sample_submission = pd.read_csv("C:/Users/82108/OneDrive/바탕 화면/git/han_river_water_level/submission_file.csv")

In [35]:
sample_submission["wl_1018662"] = pred1[0]
sample_submission["wl_1018680"] = pred2[0]
sample_submission["wl_1018683"] = pred3[0]
sample_submission["wl_1019630"] = pred4[0]

In [1]:
sample_submission.to_csv('autoanws.csv', index = False)

NameError: name 'sample_submission' is not defined

In [37]:
sample_submission

                 ymdhm  wl_1018662  wl_1018680  wl_1018683  wl_1019630
0     2022-06-01 00:00  280.602284  276.323664  274.306145  272.045663
1     2022-06-01 00:10  280.602284  276.323664  274.306145  272.045663
2     2022-06-01 00:20  280.602284  276.323664  274.306145  272.045663
3     2022-06-01 00:30  280.602284  276.323664  274.306145  272.045663
4     2022-06-01 00:40  280.602284  276.323664  274.306145  272.045663
...                ...         ...         ...         ...         ...
6907  2022-07-18 23:10  280.602284  276.323664  274.306145  272.045663
6908  2022-07-18 23:20  280.602284  276.323664  274.306145  272.045663
6909  2022-07-18 23:30  280.602284  276.323664  274.306145  272.045663
6910  2022-07-18 23:40  280.602284  276.323664  274.306145  272.045663
6911  2022-07-18 23:50  280.602284  276.323664  274.306145  272.045663

[6912 rows x 5 columns]